plugins:
  issue_comment.created: # or any other event
    - uses: # sequence of plugins to run
        - plugin: ubq-testing/issue-spec-rewrite:compute.yml@development
          name: issue-spec-rewrite
          id: issue-spec-rewrite
          type: github 
          description: "Allows GPT to rewrite the issue spec based on the evolution of the conversation across comments and linked issues."
          command:  "/rewrite" 
          example: "/rewrite"
          with: 
            keys:
              openAi: ""
            disabledCommands: []
